### ISSUE TITLE
Could not access static property

### ISSUE THREAD

**Issue by aojava** [sdaschner/jaxrs-analyzer-maven-plugin#14]
Hallo,

vielen Dank für die Vorstellung des jaxrs-analyzers auf dem Netbeansday gestern in München. So vielversprechend die Präsentation auch aussah, so ernüchternd ist leider das Ergebnis in einem Real-World-Projekt (siehe unten). Gibt es eine Chance, dass das Problem gelöst wird?

Vielen Dank für Ihre/Deine (je nach Wunsch) Antwort.

```
--- jaxrs-analyzer-maven-plugin:0.9:analyze-jaxrs (default) @ central ---
analyzing JAX-RS resources, using AsciiDoc backend
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.activedirectorysso.ActivedirectorySsoAuthenticator
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.foo.bar.central.config.Permission
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.lib.auth.PermissionDetails$AttendanceState
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.SessionManager
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.activedirectorysso.ActivedirectorySsoAuthenticator
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.activedirectorysso.ActivedirectorySsoAuthenticator
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.activedirectorysso.ActivedirectorySsoAuthenticator
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.SessionManager
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.foo.bar.central.config.Permission
Could not access static property, reason: de.company.foo.bar.central.lib.auth.BarUserSubject$Type
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.lib.auth.PermissionDetails$AttendanceState
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.BarAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.Foo56AuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.LdapAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.ActivedirectoryFastbindAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.lib.auth.Authenticator$Type
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.SessionManager$1
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.SessionManager
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.webutils.errors.CommonError
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.ActivedirectoryFastbindAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.BarAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.Foo56AuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.AuthenticatorManager
Could not analyze sub-resource class 
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.LdapAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.AuthenticatorManager
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.Foo56AuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.LdapAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.auth.presentation.JaxRsAuthenticators
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.BarAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.Foo56AuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.ActivedirectoryFastbindAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.LdapAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.auth.business.entity.ActivedirectoryFastbindAuthenticatorDescriptor$MatchField
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.AuthenticatorManager
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.messages.presentation.JaxRsMessages
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Languages
Could not access static property, reason: de.company.foo.bar.central.config.Config$Languages
Could not access static property, reason: de.company.foo.bar.central.messages.presentation.JaxRsMessages
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.common.datatypes.RecId
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.database.business.control.StoredProcedures
Could not access static property, reason: de.company.foo.bar.central.config.Config$Authenticators$AdSso
Could not access static property, reason: de.company.foo.bar.central.auth.business.control.SessionManager
```

**Comment by sdaschner** [comment]
Hallo,

Danke, dass _Du_ das Projekt mal ausprobierst :-)

Das Problem mit den static Properties (sehr oft Enums) ist bekannt und liegt an dem Javassist Framework, welches intern verwendet wird. Für die Analyse wird versucht, statische Werte zugänglich zu machen, um bestimmte Informationen zu erhalten. Kurzum: ClassLoading-Problem.

Das Ganze wird in naher Zukunft besser werden, sobald ich mit der Umstellung auf ASM durch bin. Danach wird alles vom Java Standard ClassLoader geladen.

Trotz obigen Fehlermeldungen sollte aber die Analyse durchlaufen und Ergebnisse liefern, oder? Meistens machen die statischen Properties eh keinen Unterschied für das Ergebnis...

Vorschlag: Ich gebe in diesem Issue Bescheid, sobald ich mit der Umstellung durch bin und eine Snapshot-Version getestet werden kann. Dann würde ich dich bitten, die Analyse nochmal laufen zu lassen (oben sind noch Fehler bzgl. SubResourcen, die sollten nicht sein).

**Comment by aojava** [comment]
> Trotz obigen Fehlermeldungen sollte aber die Analyse durchlaufen und Ergebnisse liefern, oder? ´

Ergebnisse ja, aber nicht immer korrekt. Beispiel:

```
  @GET
  @Path("locales")
  public LocalesDto getLocales(@QueryParam("all") boolean all) {
    Set<Locale> locales;
    if (all) {
      locales = new HashSet<>(this.messagesBoundary.getAllLocales());
    } else {
      locales = this.messagesBoundary.getActiveLocales();
    }
    Set<String> parsableLocales = Config.Languages.LOCALES.toParsableStringSet(locales);
    LocalesDto localesDto = new LocalesDto(parsableLocales);
    return localesDto;
  }
```

liefert

```
== `GET resources/i18n/locales`

=== Request
_No body_ + 
*Query Param*: all, boolean + 

=== Response
*Content-Type*: `application/json`

==== `200 OK`
*Response Body*: (`de.aidaorga.aida.ewas.central.messages.presentation.dto.LocalesDto`) + 
`application/json`: `{"locales":{}}` + 
```

wobei das Dto wie folgt aussieht:

```
public class LocalesDto {

  private String[] locales;

  public LocalesDto() {
  }

  public LocalesDto(Set<String> parsableLocales) {
    this.locales = parsableLocales.toArray(new String[0]);
  }

  public String[] getLocales() {
    return this.locales;
  }

  public void setLocales(String[] locales) {
    this.locales = locales;
  }

}
```

Der Typ der Locales geht ihm da irgendwie durch die Lappen. Erwartet hätte ich:

```
`application/json`: `{"locales":["string"]}` + 
```

**Comment by aojava** [comment]
> Vorschlag: Ich gebe in diesem Issue Bescheid, sobald ich mit der Umstellung durch bin und eine Snapshot-Version getestet werden kann.

OK.

**Comment by sdaschner** [comment]
Update: Diese Woche habe ich (endlich) die `0.10` Version publizieren können. Ist das Problem damit behoben?

**Comment by aojava** [comment]
```
Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs (default) on project central: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs (default) on project central: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.10:analyze-jaxrs failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: java.lang.NullPointerException
    at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.SubResourceLocatorMethodContentAnalyzer.determineReturnTypes(SubResourceLocatorMethodContentAnalyzer.java:75)
    at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.SubResourceLocatorMethodContentAnalyzer.analyze(SubResourceLocatorMethodContentAnalyzer.java:53)
    at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:24)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
    at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:18)
    at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:100)
    at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:64)
    at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
```

**Comment by kirchnerm** [comment]
Hallo,
wir haben hier leider das gleiche Problem mit der 0.10:

		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
		... 21 more
	Caused by: java.lang.ExceptionInInitializerError
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.InstructionBuilder.getStaticValue(InstructionBuilder.java:320)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.InstructionBuilder.buildFieldInstruction(InstructionBuilder.java:35)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.classes.ProjectMethodVisitor.visitFieldInsn(ProjectMethodVisitor.java:134)
		at org.objectweb.asm.ClassReader.a(Unknown Source)
		at org.objectweb.asm.ClassReader.b(Unknown Source)
		at org.objectweb.asm.ClassReader.accept(Unknown Source)
		at org.objectweb.asm.ClassReader.accept(Unknown Source)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.visitProjectMethod(MethodContentAnalyzer.java:122)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.addProjectMethods(MethodContentAnalyzer.java:104)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.MethodContentAnalyzer.findProjectMethods(MethodContentAnalyzer.java:87)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:58)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:26)
		at java.lang.Iterable.forEach(Iterable.java:75)
		at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.BytecodeAnalyzer.analyzeBytecode(BytecodeAnalyzer.java:18)
		at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:100)
		at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:64)
		at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:165)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
		... 21 more
	Caused by: java.lang.NumberFormatException: null
		at java.lang.Integer.parseInt(Integer.java:542)
		at java.lang.Integer.parseInt(Integer.java:615)
		at com.banking.online.autho.util.SessionUtil.<clinit>(SessionUtil.java:38)
		... 42 more

Gibt es hierzu mittlerweile eine Lösung ?

**Comment by sdaschner** [comment]
Die Issues betreffen verschiedene Bereiche.

@aojava Das Problem betrifft keine statischen Properties sondern die Analyse von sub resource locator methoden (die vermutlich nicht direkt implementiert sind, abstract, etc.). Das Ganze teste ich mal und lege dazu einen eigenen Issue an.

@kirchnerm Das Problem betrifft statische Properties, die der Analyzer beim Laden versucht zu initialisieren. In einem Constructor-Code ist wohl noch mehr Logik, die das dann pauschal verhindern. Alles, was ich an der Stelle machen kann, ist alle Exceptions zu unterdrücken (falls du in den Code geschaut hast, ich fange das für ein paar Reflection-Exceptions ab) und mit der Analyse weiterzumachen.

**Comment by sdaschner** [comment]
@kirchnerm Ich habe das umgestellt, könntet ihr das bitte mit der `0.11-SNAPSHOT` Version re-testen?

**Comment by magethle** [comment]
Ich habe dasselbe Problem mit der Version 0.14 bei statischen properties wie z.B.  

> private final static Logger logger = Logger.getLogger(MyClass.class);

oder

> private static final double[] ARRAY = new double[] {11, 58, 13, 59};

Gibt's dafür eine Lösung oder ein workaraound?  
Ansonsten ist dieses plugin sehr praktisch :+1:

**Comment by sdaschner** [comment]
Nein, aktuell nicht, bei ein paar Sonderfällen wird die Analyse von statischen Properties (z. B. mit Dynamik beim Initialisieren) nicht möglich sein...

**Comment by reddyalready** [comment]
Hi Sebastian,

Thanks a lot for your work on this so far, this library is super easy to use and generates great documentation.

We are having trouble with enums, e.g.:

```
Could not access static property, reason: com.test.log.EventName
java.lang.ClassNotFoundException: com.test.log.AsmEventName
```

`EventName` for example, is a public enum. Is there no solution in v0.15? If I can contribute something to fix this with your guidance, happy to do so!

**Comment by rmannibucau** [comment]
Hi @sdaschner ,

what about updating com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.collection.InstructionBuilder#buildFieldInstruction GETSTATIC handling with:

    final Object val = value == null ? name : value;
    return new GetStaticInstruction(ownerClass, name, desc, val, label);

This would simulate enum handling and would allow to remove the warning. To be more accurate we can also visit the missing type and just detect it is an enum. Doing so you don't even never need to load the type in getStaticValue().

**Comment by sco0ter** [comment]
I am still having this issue with version 0.16.

It affects ```private static final Logger``` instances, but more importantly also public enums (which static by nature).

**Comment by kappaj2** [comment]
Also running into the static error with Logger definitions.
Is there a way to suppress these errors to get just a basic Swagger doc to start with?
