### ISSUE TITLE
StackOverflowError while generating asciidoc

### ISSUE THREAD

**Issue by wumpz** [sdaschner/jaxrs-analyzer-maven-plugin#31]
Gleiches Projekt wie bei #30. 

Stelle ich die Ausgabe von swagger auf asciidoc um, erhalte ich folgende Exception, nun allerdings direkt aus dem jaxrs-analyzer. Die Exception hab ich schon verkürzt, da wie schon gesagt hier eine Endlosschleife entstanden zu sein scheint, bzw. eine die der Stack nicht mehr verkraftet.

Exception in thread "main" java.lang.StackOverflowError
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.visit(JsonRepresentationAppender.java:40)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$ConcreteTypeRepresentation.accept(TypeRepresentation.java:130)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$CollectionTypeRepresentation.accept(TypeRepresentation.java:173)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.lambda$visit$0(JsonRepresentationAppender.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.visit(JsonRepresentationAppender.java:40)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$ConcreteTypeRepresentation.accept(TypeRepresentation.java:130)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$CollectionTypeRepresentation.accept(TypeRepresentation.java:173)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.lambda$visit$0(JsonRepresentationAppender.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.visit(JsonRepresentationAppender.java:40)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$ConcreteTypeRepresentation.accept(TypeRepresentation.java:130)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$CollectionTypeRepresentation.accept(TypeRepresentation.java:173)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.lambda$visit$0(JsonRepresentationAppender.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.visit(JsonRepresentationAppender.java:40)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$ConcreteTypeRepresentation.accept(TypeRepresentation.java:130)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$CollectionTypeRepresentation.accept(TypeRepresentation.java:173)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.lambda$visit$0(JsonRepresentationAppender.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.visit(JsonRepresentationAppender.java:40)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$ConcreteTypeRepresentation.accept(TypeRepresentation.java:130)
	at com.sebastian_daschner.jaxrs_analyzer.model.rest.TypeRepresentation$CollectionTypeRepresentation.accept(TypeRepresentation.java:173)
	at com.sebastian_daschner.jaxrs_analyzer.backend.JsonRepresentationAppender.lambda$visit$0(JsonRepresentationAppender.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

**Comment by sdaschner** [comment]
Einen sehr ähnlichen Fehler hatte schonmal jemand eingestellt gesucht, ein minimaler Reproducer wäre extrem hilfreich. Gerne direkt in das [jaxrs-analyzer-st](https://github.com/sdaschner/jaxrs-analyzer-st) Projekt :-)
