### ISSUE TITLE
Missing org/apache/tomcat/util/buf/ByteChunk$ByteOutputChannel

### ISSUE THREAD

**Issue by edelfinato** [sdaschner/jaxrs-analyzer-maven-plugin#32]
When I run mvn install -X  I got the following error:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.889 s
[INFO] Finished at: 2017-03-01T15:58:55+01:00
[INFO] Final Memory: 54M/624M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14:analyze-jaxrs (default) on project hypebusin
essdashboard-core: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14:analyze-jaxrs failed: A requir
ed class was missing while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14:analyze-jaxrs: org/apache/tomcat/util/
buf/ByteChunk$ByteOutputChannel
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.14/jaxrs-analyzer-maven
-plugin-0.14.jar
[ERROR] urls[1] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.14/jaxrs-analyzer-0.14.jar
[ERROR] urls[2] = file:/C:/Users/cona77/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.apache.tomcat.util.buf.ByteChunk$ByteOutputChannel
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0
.14:analyze-jaxrs (default) on project cona77-pro: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-
maven-plugin:0.14:analyze-jaxrs failed: A required class was missing while executing com.sebastian-daschner:jaxrs-analyzer-maven-pl
ugin:0.14:analyze-jaxrs: org/apache/tomcat/util/buf/ByteChunk$ByteOutputChannel
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.14/jaxrs-analyzer-maven-plugin-
0.14.jar
urls[1] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.14/jaxrs-analyzer-0.14.jar
urls[2] = file:/C:/Users/cona77/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.sebastian-daschner:jaxrs-analyzer-maven-
plugin:0.14:analyze-jaxrs failed: A required class was missing while executing com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0
.14:analyze-jaxrs: org/apache/tomcat/util/buf/ByteChunk$ByteOutputChannel
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.14/jaxrs-analyzer-maven-plugin-
0.14.jar
urls[1] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.14/jaxrs-analyzer-0.14.jar
urls[2] = file:/C:/Users/cona77/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:168)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing com.sebastian-daschner:ja
xrs-analyzer-maven-plugin:0.14:analyze-jaxrs: org/apache/tomcat/util/buf/ByteChunk$ByteOutputChannel
-----------------------------------------------------
realm =    plugin>com.sebastian-daschner:jaxrs-analyzer-maven-plugin:0.14
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer-maven-plugin/0.14/jaxrs-analyzer-maven-plugin-
0.14.jar
urls[1] = file:/C:/Users/cona77/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.14/jaxrs-analyzer-0.14.jar
urls[2] = file:/C:/Users/cona77/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:166)
        ... 21 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/util/buf/ByteChunk$ByteOutputChannel
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.findMethod(JavaUtils.java:399)
        at com.sebastian_daschner.jaxrs_analyzer.model.JavaUtils.findMethod(JavaUtils.java:394)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.classes.JAXRSClassVisitor.hasJAXRSAnnotations(JAXRSClassVisitor.java:95)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.classes.JAXRSClassVisitor.visitMethod(JAXRSClassVisitor.java:78)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyzeClass(ProjectAnalyzer.java:134)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:105)
        at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute(JAXRSAnalyzerMojo.java:194)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.buf.ByteChunk$ByteOutputChannel
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 47 more
```

Let me know if you need more information. Thanks

**Comment by sdaschner** [comment]
Thanks for issuing.

Are you using the Maven `3.3.9` version? From which dependency does `org.apache.tomcat...ByteChunk` come from? Could be a dependency mismatch issue...

**Comment by edelfinato** [comment]
Thanks for your answer. 
Yes I'm using Apache Maven 3.3.9. I don't use that class in my project and I can't import org.apache.tomcat.util.buf in the project. I haven't any ideas where it come from. Are there some methods to check where that class come from?

**Comment by sdaschner** [comment]
Yes, either using the IDE (i.e. search for that class and "show in tree"), or use the maven dependency plugin. How does your pom.xml look like?

**Comment by edelfinato** [comment]
I resolved. It was a dependency mismatch issue. It was caused by securitycore-tomcat artifact, I removed that dependecy and refactored some class and it worked.
Thanks for the support.
